### ISSUE TITLE
Issues with stylesheet files

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/srclib-css#13]
- we don't care when there is no such a file. Does it make sense to emit refs to not-existent one?
```html
<link rel="stylesheet" href="there-is-no-spoon.css"/>
```

- If stylesheet points to relative URL I think it would be better to normalize its path

```html
<link rel="stylesheet" href="../root.css"/>
```

- Stylesheet may point to absolute URL, we may exclude them from the processing (or emit proper DefRepo and DefUnit)
```html
<link rel="stylesheet" href="//google.com/style.css">
```

- Stylesheet may contain query string or hash which probably should be ignored
```html
<link rel="stylesheet" href="style.css?v=20160531100000">
```

**Comment by chris-ramon** [comment]
> we don't care when there is no such a file. Does it make sense to emit refs to not-existent one?

If such a file does not exist, atm `srclib-css` does not emit refs.

> If stylesheet points to relative URL I think it would be better to normalize its path

Good call Alex! - Addressed on: https://github.com/sourcegraph/srclib-css/pull/17/files#diff-a16471055e07a5dfd4d03aec2d1e38fbR419

> Stylesheet may point to absolute URL, we may exclude them from the processing (or emit proper DefRepo and DefUnit)

By now we do [ignore them](https://github.com/sgtest/css-sample-0/blob/master/main.html#L10), perhaps we'll support analyzing external stylesheets resource sometime soon.

> Stylesheet may contain query string or hash which probably should be ignored

I don't think we should be ignoring the query string part, because if we do: we would be ignoring a file with an actual name: `style.css?v=20160531100000`

**Comment by chris-ramon** [comment]
Feel free to create a new issue for not-supported-yet features, as mentioned above:
- Analyze external CSS stylesheets.
